### PR TITLE
fix #129: calling @vlplot with data keyword

### LINKED ISSUE #129: Empty plot when using data keyword in @vlplot
I found an example ([gist](https://gist.github.com/leethargo/6a41060ae93abb6be786c191df7703bc)) which works as expected when I use the `data |> @vlplot` syntax, but fails when I use `@vlplot(..., data=data)` syntax.

According to the [docs](http://fredo-dedup.github.io/VegaLite.jl/stable/userguide/data.html#Using-inline-data-with-the-data-keyword-1), these two approaches should be equivalent, right?

My motivation for using the keyword `data` is that I want to layer two charts that each use different datasets, so I can't just pipe one table into the `@vlplot() + @vlplot` expression.

### PR DESCRIPTION
**Pull request by leethargo**

### CODE REVIEW

**Comment by leethargo** [comment]
There is some copy&paste code and I added more to it, so this should probably be refactored a bit.

**Comment by leethargo** [comment]
Also, while I did find and fix a difference between `@vlplot(data=d)` and `@vlplot()(d)`, my original example in #129 still applies, I fear (empty plot with warnings). Or else, I failed to execute the notebook from the correct `Pkg` environment.

**Comment by leethargo** [comment]
I added two functions for code reuse, but did not really know where to place them, so they are in [vlspec.jl](https://github.com/fredo-dedup/VegaLite.jl/blob/f1f8ba3731b3e8d8bee641cb2e3f12b73250dab1/src/vlspec.jl#L12) now, where they are also called.

**Comment by davidanthoff** [comment]
Thanks a lot, this is exactly right, plus it also cleans up the existing old code, much appreciated!

**Pull request merged**
