### PR TITLE
Add support for the pipe operator

### PR DESCRIPTION
**Pull request by davidanthoff**
This enables the following syntax:
````julia
DataFrame(x=randn(200)) |> data_values() |>
    mark_bar() |>
    encoding_x_quant(:x; bin=Dict(:maxbins=>20), axis=Dict(:title=>"values")) |>
    encoding_y_quant(:*, aggregate="count", axis=Dict(:title=>"number of draws"))
````
In itself probably not a huge improvement over the existing ``+`` (although ``ggvis`` also uses pipes instead of ``+``, so there is some precedence).

But I hope to enable a dplyr like interface for [Query.jl](https://github.com/davidanthoff/Query.jl), and at that point it might make for a nice overall UI experience, i.e. one could pipe all the way from say a csv load, through some query manipulations into a plot.

### CODE REVIEW

**Comment by fredo-dedup** [comment]
In the devl branch I am currently moving away from VegaLite specs built by adding pieces (with `+` or `|>`) because the VegaLite JSON schema is rather deep and with identical property names appearing at different places (`tick`, `axis` etc..) so it becomes ambiguous if, for example, a ` ... + tick(..)` is added. 
Unless I keep that option only for the root level, IDK.

Currently in devl, I am using nested function calls with a `plot(..)` at the root level. Either the property is a scalar or string and you use a keyword argument, or it is a structure and then you use a function (with a leading underscore to avoid name collisions with Base), for example : 
```julia
durl = "https://raw.githubusercontent.com/vega/new-editor/master/data/movies.json"

plot(_data(url=durl),
     mark="circle",
     _encoding(_x(_bin(maxbins=10), field="IMDB_Rating", typ="quantitative"),
               _y(_bin(maxbins=10), field="Rotten_Tomatoes_Rating", typ="quantitative"),
               _color(field="Rotten_Tomatoes_Rating", typ="quantitative"),
               _size(aggregate="count", typ="quantitative")),
     width=300, height=300)
```

One advantage of keeping a syntax that maps directly to the JSON spec is that I can auto-generate all functions and associated docs from the JSON schema file of the VegaLite project. This enables an almost instant synchronization with the project at very little cost (changing the pkg.build to point to the new versions and checking that the auto-generation still passes and that docs are not mangled). 

Do you think that keeping the additive syntax (with `+` or `|>` ) is a key feature ?

**Comment by davidanthoff** [comment]
Hm, interesting... I kind of like the composition via some operator at the root level, especially given the ggplot precedent. It kind of allows for a simple building up of figures.

I think the idea that one can pipe something into a plot would work with the new design in any case, though. The code might look like:
````julia
load("data.csv") |> 
    plot(
     mark="circle",
     _encoding(_x(_bin(maxbins=10), field="IMDB_Rating", typ="quantitative"),
               _y(_bin(maxbins=10), field="Rotten_Tomatoes_Rating", typ="quantitative"),
               _color(field="Rotten_Tomatoes_Rating", typ="quantitative"),
               _size(aggregate="count", typ="quantitative")),
     width=300, height=300)
````
I completely understand the desire to match the upstream schema automatically, but I have to say that the API here seems to look quite a bit less attractive relative to what is on ``master`` right now... The underscores in particular seem odd, my sense is that they are emerging as a convention for "private" field members, and to see them in a public API now seems odd. It also seems that a whole bunch of things that were ``Symbol``s previously are now ``String``s? That also seems less convenient.

To be honest, my first reaction to the original design on ``master`` was "finally a ggplot like API that still looks really julia native", whereas this looks much more like something that an automatic wrapper would create, but not like something that really fits into the julia style or would be easy and pleasant to use...

Maybe one could have the automatically generated stuff as the bottom layer, but then provide another user facing API on top of that that looks more like the old API? I'm not sure that would really buy us much, but maybe worth a thought?

**Comment by davidanthoff** [comment]
@fredo-dedup I'm now done integrating my whole [IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl) and [Query.jl](https://github.com/davidanthoff/Query.jl) framework with [FileIO.jl](https://github.com/JuliaIO/FileIO.jl) and a general pipe syntax. If we could merge this here, it would enable some really nice flows:
````julia
load("data.csv") |>
    @query(i, begin
        @group i by i.children into g
        @select {children = g.children, age = mean(g..age)}
    end |>
    data_values() |>
    mark_bar() |>
    encoding_x_quant(:x; bin=Dict(:maxbins=>20), axis=Dict(:title=>"values")) |>
    encoding_y_quant(:*, aggregate="count", axis=Dict(:title=>"number of draws")) |>
    save("output.pdf")
````
There is support for quite a wide range of file formats, both on the load and the save front.

Note in particular that I managed to reuse the ``save`` function in ``FileIO.jl`` to save plots and you can use that to save in multiple formats.

It would be great if I could show-case all of this in my juliacon talk on Query.jl. Do you think there is a chance that you could merge this PR and then tag a version based on the current ``master`` sometime early this week? And then maybe not tag anything based on ``devel`` until after juliacon? That would give me a) enough time to have a tagged version to prep my talk and b) make sure that I have the stable, current ``master`` version as the tagged version during the course of juliacon. Btw., are you coming to juliacon?

**Comment by davidanthoff** [comment]
Cool, thanks, much appreciated!!

**Pull request merged**
