### PR TITLE
Use NodeJS

### PR DESCRIPTION
**Pull request by davidanthoff**
This is all a bit rough still, but in general this should pretty much work. This implements my suggestion in #10.

~~The PNG export looks strange right now, it seems to sometimes clip the graph. But that can probably be sorted out.~~ I also think there are more file formats supported by Cairo, so we should be able to offer even more formats using this general strategy.

~~Not ready to merge because NodeJS.jl is not yet registered.~~ Also, not clear to me whether this should be merged into ``master`` or some other process.

6/1/2017: The png problem was a mistake on my side when looking at the file, this is all working.
6/1/2017: NodeJS.jl is now registered.

### CODE REVIEW

**Comment by fredo-dedup** [comment]
Hi @davidanthoff,

Thanks for this PR. I'll need some time to evaluate this fully because I am currently upgrading this package to VegaLite v2 and I am close to finished. Among the upgrades I have already added support for file exports through the PhantomJS package (a separate executable that processes html files and can "print" the page to a file in different formats). But your approach with Node may be superior (in speed notably).

Just to check that I understand correctly : 
- VegaLite needs also to be loaded with npm (this is what you do in build.jl), right ? Why not use the executables that are part of vegalite ( vn2png, vn2svg ) ? Do they require the npm install too ?
- For the output to file functions, I add in mind a syntax closer to the one used in plots.jl : `png(path, plot)`, `jgp(path, plot)`, etc.
- Node can only export in svg ? This is the reason for the new dependency with Cairo and Rsvg ? 
- Does the whole thing work on Windows ? I have vague memories of issues due to lacking libraries with Node on Windows.

**Comment by davidanthoff** [comment]
> VegaLite needs also to be loaded with npm (this is what you do in build.jl), right ?

Yes

> Why not use the executables that are part of vegalite ( vn2png, vn2svg ) ? Do they require the npm install too ?

vn2png and vn2svg are just javascript files, so they also require a nodejs installation (and vega-lite via npm) to run. Both of these scripts don't work on Windows. The script ``compilesvg.js`` in this PR is essentially a copy of the content of those two files, with the Windows problems fixed.

> For the output to file functions, I add in mind a syntax closer to the one used in plots.jl : ``png(path, plot)``, ``jgp(path, plot)``, etc.

Yeah, that would work as well. It would be nice if there was a canonical way to do this in julia, but that would probably take a lot of coordination. I'll add the functions you suggested, that should be really simple.

> Node can only export in svg ? This is the reason for the new dependency with Cairo and Rsvg ?

vega-lite can export to svg and png if run under node. But the png export requires a working cairo installation *for node*, and I couldn't get that to work on Windows. Cairo.jl on the other hand handles all the binary dependencies just fine on all platforms, so that seemed much easier. So yes, Cairo and Rsvg are what I use to convert things to other formats than svg. I also looked for other nodejs packages that can convert between image formats, but they all require Cairo for nodejs, so I always ran into the problem that I couldn't get that to run on Windows.

> Does the whole thing work on Windows ? I have vague memories of issues due to lacking libraries with Node on Windows.

Yes, I'm on Windows, so that is the most tested configuration. I also tried it on Ubuntu and that seemed to work. I don't have a Mac for testing.

**Comment by davidanthoff** [comment]
Alright, I've added ``png`` etc. functions. I'm also trying to figure out the whole FileIO.jl package. It seems to provide a general ``save`` function that might allow something like ``save("filename.png", p)``, but I don't understand fully right now how that is supposed to work...

**Comment by davidanthoff** [comment]
See JuliaIO/FileIO.jl#122 for my question re FileIO.jl integration.

**Comment by fredo-dedup** [comment]
To keep you from waiting that I finish my upgrade work in the devl branch, I am ok to merge this on master when you think it is ready. (some tests would be nice if you have time for that).
I will port them on the devl branch. 
I may add also a choice of the printing backend : node or phantomjs for the user to chose if it makes sense.

**Comment by davidanthoff** [comment]
@fredo-dedup Alright, I think this is ready to go, now with tests.

**Comment by fredo-dedup** [comment]
Thanks David !

**Pull request merged**
